### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ghost** [gta5-map/Social-Club-example-parser#1]
Doesn't work anymore.
Rockstar has changed the way to login yesterday and I got a 403 error on the login page.

**Comment by frdmn** [comment]
Hey @y8hamon,

I just retried and it still works for me:

![bildschirmfoto 2015-02-03 um 18 48 39](https://cloud.githubusercontent.com/assets/944459/6026567/0c1630d0-abdc-11e4-8cab-c0ab58fbe0a9.png)

Why do you assume they've changed anything yesterday?

**Comment by ghost** [comment]
Hey,

Thanks for your answer. Have you tried to acess this page for example (Right after logging in) ?
http://socialclub.rockstargames.com/reference/profilefeed/[PROFILE_ID]?offset=0 (Replace PROFILE_ID with your Rockstar ID, ie a number you can find if you parse the /member/YOUR_NICKNAME page.

I've coded something similar to yours, a year ago, and it was fully working until yesterday. 
Now I got a 403 with my script or yours.

**Comment by frdmn** [comment]
@y8hamon Works for me as well:

![bildschirmfoto 2015-02-03 um 19 37 45](https://cloud.githubusercontent.com/assets/944459/6026586/376d4610-abdc-11e4-989a-42500b4c362e.png)

I just replaced line [63](https://github.com/gta5-map/Social-Club-example-parser/blob/master/index.php#L63) with:

```
curl_setopt($ch, CURLOPT_URL,"http://socialclub.rockstargames.com/reference/profilefeed/47990204?offset=0");
```

(47990204 is my profile id)

**Comment by ghost** [comment]
Hey,

I have the following response replacing your ID with mine:

```
{"Status":0,"Message":null,"Error":{"Code":"Common.NotAuthorised","CodeEx":null,"CodeLong":"Common.NotAuthorised","_message":"","Message":"","Context":null,"_msg":"","Location":null,"ContextProperty":null}}
```

I've tried with both my username and my email as argument, and I got the exact same response.

Moreover, `$buf2` seems not to contain any character (empty string). I'm almost certain it should contain the content of /member/USERNAME. Could you confirm that ?

**Comment by frdmn** [comment]
@y8hamon And if you use the ID that i provided, you get the same result?

Regarding `$buf2`: That variable doesn't return a string (Since it doesn't use `curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);`). It retruns a boolean value instead. So it's either `true` or `false`.

Can you give me the ID that you use in your "failed case", then I can try to reproduce.

**Comment by ghost** [comment]
@frdmn I've used both, yours (47990204) and mine (20567916).
Actually, `$buf2` returns nothing.
If you have an email adress I can send you my credentials (Nothing really important to protect).

**Comment by frdmn** [comment]
I'd rather prefer IRC, then we can also chat and try to fix it. You can send it there in private to me. I am available in Freenode and EsperNet as "frdmn". If you don't have a native IRC client:

http://webchat.esper.net/?channels=%23yeahwhat

**Comment by frdmn** [comment]
Can't reproduce @y8hamon's problem, even with his credentials. Script still works fine.

We assume it's an issue related to the PHP version (5.2) or his server. Will report back if we get this fixed.

**Comment by ghost** [comment]
Problem solved. Apparently, this doesn't work if you try to reach english rockstar servers from a french IP. Solved with a proxy.

**Comment by frdmn** [comment]
@y8hamon great to hear, you've got this sorted. In case you have any other issues or suggestions, feel free to open another issue.
