### ISSUE TITLE
No Information

### ISSUE THREAD

**Issue by Sander0542** [gta5-map/Social-Club-example-parser#10]
This is what I get when I use google chrome

`[DEBUG] Configuration file loaded. [DEBUG] [checkExistingCookieJar] Found existing cookie file. [DEBUG] [parseActualInformation] Sending request to parse actual data. [DEBUG] [checkForEmptyData] Empty/fake data detected. [DEBUG] [renewAuthentication] Sending request to parse the login form. [DEBUG] [renewAuthentication] Received RequestVerificationToken: ''. [DEBUG] [renewAuthentication] Sending authentication request. [DEBUG] [checkForCaptchaRequest] No captcha request detected. [DEBUG] [renewAuthentication] Successfuly authenticated. [DEBUG] [parseActualInformation] Sending request to parse actual data.`

**Comment by frdmn** [comment]
Please retry using version 1.4.0:

https://github.com/gta5-map/Social-Club-example-parser/releases/tag/1.4.0
