### ISSUE TITLE
AuthenticateCookie not been written to cookie_jar.txt

### ISSUE THREAD

**Issue by mattkirwan** [gta5-map/Social-Club-example-parser#2]
Hi,

I've been running around in circles and can't seem to figure out why my cookie_jar.txt file isn't writing all requests (Eg: it's only writing the cookies from the first (get __RequestVerifacationToken) and second (visitin the login screen) - only the 3rd and onwards (AuthenticateCookie) doesn't get written (therefore I'm never allowed access.

ANy thoughts? I'm banging my head against a wall here and any lead is greatly appreciated.

Cheers,

Matt

**Comment by mattkirwan** [comment]
I've figure this out. It looks like there is some kind of communication issues with SSL (I can't work out whether it's not liking 'switching' between http and https but after some muddling through it and coming up with a more verbose set of CURL_OPT's it is now working.

As an example:

All requests were (from my development machine [OPENSSL]) were required to be https (if one of them were):

```
        curl_setopt($ch, CURLOPT_COOKIEFILE, "/path/to/cookie_jar.txt");
        curl_setopt($ch, CURLOPT_URL,"https://socialclub.rockstargames.com/profile/signin");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
        curl_setopt($ch, CURLOPT_CAINFO, "/path/to/ssl.crt");
        curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, "TLSv1");
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
```

Again, I don't fully understand why (possibly also something to do with SSL3 (R*'s SSL Cert), if you think this would be useful, just reply and I'll drop in a PR for the README/CheatSheet.

Cheers for an epic outline of their (rather shitty) "API".

**Comment by frdmn** [comment]
@mattkirwan Thank you for reporting this. I didn't try out the parser the past couple of days, so maybe R\* changed something on their end.

I'll let you know if your PR is needed :)
