### ISSUE TITLE
Rewrite example parser

### ISSUE THREAD

**Issue by frdmn** [gta5-map/Social-Club-example-parser#5]
As discussed in gta5-map/Social-Club-API-cheat-sheet#1 and gta5-map/Social-Club-API-cheat-sheet#3, the implementation of ReCaptcha by R*, kinda broke the current example parser. 

Refactor time!

**Comment by frdmn** [comment]
@r3m4k3 @thecrossandcrown Can you guys try version [1.2](https://github.com/gta5-map/Social-Club-example-parser/commit/e2ebdaa77aaba8eb21cca0a7a899ebdb56105405) from master branch?

**Comment by thecrossandcrown** [comment]
Done... looking good. Have been refreshing periodically over 6 hours. Haven't been prompted with a captcha request so can't comment on that.

[DEBUG] Configuration file loaded. [DEBUG] [checkExistingCookieJar] Found existing cookie file. [DEBUG] [parseActualInformation] Sending request to parse actual data. [DEBUG] [checkForEmptyData] No empty/fake data detected

Debug looking good. Great work. Thank you!

**Comment by frdmn** [comment]
@thecrossandcrown Great to hear that. I'm going to add some final improvements to bring the parsed data into a pretty format like JSON as well.
