### ISSUE TITLE
Set proper data types for integers, booleans, etc.

### ISSUE THREAD

**Issue by frdmn** [gta5-map/Social-Club-example-parser#6]
At the moment almost everything is returned as a string in the JSON output.

**Comment by thecrossandcrown** [comment]
Oh my god I didn't realise the turn over would be so quick. _squeels like a girl_ Will test it in an hour or so. Thank you too much.

**Comment by frdmn** [comment]
Haha, let me know how it went and feel free to report any kind of suggestions or feedback! :+1:

**Comment by thecrossandcrown** [comment]
Got a 500 server error on new update. Will get the error logs at lunch.

**Comment by frdmn** [comment]
@thecrossandcrown Could you already check your logs? I couldn't really reproduce any 500 error here.

**Comment by frdmn** [comment]
@thecrossandcrown Gonna close this issue for now since it's probably not really related to your problem. Feel free to open a new one as soon as you have more informations! :)

**Comment by thecrossandcrown** [comment]
Yeah totally. Didn't have time yesterday. Apolgies

**Comment by frdmn** [comment]
@thecrossandcrown No worries!
