### ISSUE TITLE
Everything is zero

### ISSUE THREAD

**Issue by coolnickname** [gta5-map/Social-Club-example-parser#8]
Like I said, all values return 0. I set debug to true and get no errors.
This is probably my fault, though. But I don't see what I'm doing wrong?

**Comment by frdmn** [comment]
Hi, @coolnickname. That sounds really strange. 

Do you just try running the example parser? Could you give me the full output that you receive at the moment?

**Comment by coolnickname** [comment]
@frdmn

The log:
http://pastebin.com/EBvcmGSN

I just try to run index.php but I had to remove a few of the last linies because I got errors. I removed like 4 starting for line 405.

**Comment by coolnickname** [comment]
I dont know if this helps but I play on 2 different platforms so maybe it can't decide which one to select?

**Comment by coolnickname** [comment]
And if I try to get the info of another player I get this error:
`Fatal error: Uncaught Error: Call to a member function next_sibling() on null in /customers/1/0/4/yildri.nl/httpd.www/gta/info/index.php:214
Stack trace:
#0 /customers/1/0/4/yildri.nl/httpd.www/gta/info/index.php(378): calculateProgressbarStats('\r\n\r\n\r\n\r\n<!DOCTY...', 'Stamina')
#1 {main}
  thrown in /customers/1/0/4/yildri.nl/httpd.www/gta/info/index.php on line 214
`

**Comment by frdmn** [comment]
@coolnickname Hmm, I'm going to try to investigate this tomorrow or sunday and let you know.

**Comment by Bluscream** [comment]
Tomorrow or sunday lololol

**Comment by frdmn** [comment]
@Bluscream Hahaha, apologies! I have a lot of work and projects going. I try to take a look asap :)

**Comment by Bluscream** [comment]
Seriously im personally not interested into this cause i dont have any free time for gaming, i was just browsing through all my old issues :D 

But im sure others (or maaybe i) want to use this in the future =)

Also if you have some kind of webserver running somewhere it would be quite nice if you could host a version of your nice API (Good job on that by the way <3)

**Comment by frdmn** [comment]
@Bluscream I have several web servers running, but I think the problem is that they (R*) probably will shut it down pretty quickly, as all the requests would come from one single IP origin.

That way we probably would constantly run into the (CloudFlare) captcha issue and at some point they notice the mass of different gamertags that login with the same IP and they could blacklist it anyway. I don't really want to go there and     play that game of cat-and-mouse. Hope you understand.

**Comment by Bluscream** [comment]
I can m8. But what do you think is gonna happen when i link this to a livestream chat xD

**Comment by coolnickname** [comment]
I already gave up on this project, as it isn't that important xD
It would be nice if it worked, however it might be my fault I didn't get it working as I am quite clumsy :3

**Comment by frdmn** [comment]
Please try version 1.4.0 :)

https://github.com/gta5-map/Social-Club-example-parser/releases/tag/1.4.0
