### ISSUE TITLE
API does not work for me.

### ISSUE THREAD

**Issue by Bluscream** [gta5-map/Social-Club-example-parser#9]
![image](https://cloud.githubusercontent.com/assets/3318223/16710836/8ccaad98-463e-11e6-991e-8432299e6ac9.png)

```
[DEBUG] Configuration file loaded. [DEBUG] [checkExistingCookieJar] Couldn't find existing cookie file. [DEBUG] [renewAuthentication] Sending request to parse the login form. 
Notice: Trying to get property of non-object in D:\SERVERS\xampp\htdocs\api\gta\index.php on line 137
[DEBUG] [renewAuthentication] Received RequestVerificationToken: ''. [DEBUG] [renewAuthentication] Sending authentication request. [DEBUG] [checkForCaptchaRequest] No captcha request detected. [DEBUG] [renewAuthentication] Successfuly authenticated. [DEBUG] [parseActualInformation] Sending request to parse actual data. [DEBUG] [checkForEmptyData] No empty/fake data detected. 
Fatal error: Call to a member function find() on boolean in D:\SERVERS\xampp\htdocs\api\gta\index.php on line 312
```

**Comment by frdmn** [comment]
Maybe the frontend changed on R\* side and now the CSRF token cant be properly parsed? 

Based on this `Received RequestVerificationToken: ''.` it looks like that at least...

**Comment by Bluscream** [comment]
Does the API work for you? My purpose would be to implement it into a [twitch bot API](https://docs.nightbot.tv/commands/variables/urlfetch). For this of course i have to rewrite it to parse in plain text but when i get it to work that should be easy.

**Comment by frdmn** [comment]
@Bluscream As stated in #8, I'll try sure to priorize this project and check all the open issues, irks and bugs.

**Comment by frdmn** [comment]
You probably already saw the refactor of @hkors...

Closing this now :)
